var testData = {
	"children": [
		{
			"children": [
				{
					"children": [
						{
							"children": [],
							"Id": "f65d41c6-5f0e-49a2-8cc9-bc0a99c046a2",
							"Expanded": true,
							"Horizontal": true,
							"Text": "electro 2-1",
							"Description": null,
							"Volume": 70,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": -1,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": ""
						}
					],
					"Id": "a3076cfd-6a68-4b00-90e9-f0542f57e8ff",
					"Expanded": true,
					"Horizontal": true,
					"Text": "electro 1-1",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": -1,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "3a60da15-fc7e-4580-afd7-84f3003c67a4",
					"Expanded": true,
					"Horizontal": true,
					"Text": "electro 1-2",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 9999,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				}
			],
			"Id": "c1e9dad1-ed55-4dcc-8427-b53afca10590",
			"Expanded": true,
			"Horizontal": true,
			"Text": "Electro",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": -1,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [],
			"Id": "545af80b-30fb-4cdd-8315-8a3b4397f813",
			"Expanded": true,
			"Horizontal": true,
			"Text": "eASY",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 9999,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [
				{
					"children": [],
					"Id": "3523a7f3-9e0c-484e-b3d8-8152f7ed4655",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Gaming 1-1",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": -1,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				}
			],
			"Id": "c06b35a9-085e-418f-9ce8-0ffc6d8a78f4",
			"Expanded": true,
			"Horizontal": true,
			"Text": "Gaming",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 19999,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		}
	],
	"Id": "62509362-2f1e-4442-9214-ce722afda506",
	"Expanded": true,
	"Horizontal": true,
	"Text": "ZePansoft",
	"Description": null,
	"Volume": 70,
	"VolumeChanged": false,
	"Color": null,
	"LineColor": null,
	"HorizontalOrder": -1,
	"Selected": true,
	"SequentialPlayback": false,
	"BackgroundImage": null
};

var testData2 = {
	"children": [
		{
			"children": [
				{
					"children": [],
					"Id": "98e25c9b-c950-475c-a15b-f87b17d71f04",
					"Expanded": true,
					"Horizontal": true,
					"Text": "walk in the city",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 0,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "6ead1b98-74a9-4e5c-831f-dab41aa88a0a",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Alone working",
					"Description": "",
					"Volume": 48,
					"VolumeChanged": true,
					"Color": "#FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 10000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "c0f1db6f-ec1f-4f77-a12f-17f0bcc2a834",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Cristmas",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 20000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "2c8ad932-e53f-4b4c-b7e0-4da2ba799cea",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Celebrations",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 30000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "81a21d7d-7e16-43bc-8ee8-f60122d7fa3a",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Studio/concentrazione/focus",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 40000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "072924dc-4583-4b73-bced-7070d2c4e169",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Rialzati !",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 50000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "f9ce4ff7-6cc8-4418-8da1-03f6c59d68f2",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Viaggiare",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 60000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "872eea35-b568-47cd-a5f7-fe5c067840a3",
					"Expanded": true,
					"Horizontal": true,
					"Text": "pensa...cura ferite...",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 70000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "2add3693-d57c-419d-9350-1f7f65095723",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Incantation",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 80000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "4dead44f-d8c3-4db2-a41c-404916c4e27f",
					"Expanded": true,
					"Horizontal": true,
					"Text": "natura contemplazione",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 90000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "8fbf0277-091d-45d4-a580-e1fa8d3f166d",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Respiro",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 100000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "853a3845-ecf1-4f4f-a466-04839619699d",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Meditazione",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 110000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "fa62796d-94f3-4348-9b2a-be3ae07363a4",
					"Expanded": true,
					"Horizontal": true,
					"Text": "voglia di suonare",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 120000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "12631d4e-623f-4c9c-873a-102cbd9847bf",
					"Expanded": true,
					"Horizontal": true,
					"Text": "voglia di cantare",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 130000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [
						{
							"children": [],
							"Id": "90c79147-d34d-4228-b93e-a71288bc6b91",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Funny NON tunz",
							"Description": "",
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 0,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "c57721b0-d7ab-4210-8f13-04b35ea885d9",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Tunz Spensierata",
							"Description": "",
							"Volume": 100,
							"VolumeChanged": false,
							"Color": "",
							"LineColor": null,
							"HorizontalOrder": 10000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "ad2058c2-4489-42ea-a927-f4f7168f6112",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Tunz Hard",
							"Description": "",
							"Volume": 100,
							"VolumeChanged": false,
							"Color": "",
							"LineColor": null,
							"HorizontalOrder": 20000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "f1ec975b-dc58-4559-8363-ea78d03df24b",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Soft",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 30000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						}
					],
					"Id": "70860908-8347-46f2-a503-060deb5cb853",
					"Expanded": false,
					"Horizontal": false,
					"Text": "Voglia  di  ballare",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 140000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "9bb60da2-a8f8-41c6-bea9-8c18fb9862dc",
					"Expanded": true,
					"Horizontal": true,
					"Text": "training",
					"Description": "",
					"Volume": 87,
					"VolumeChanged": true,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 150000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [
						{
							"children": [],
							"Id": "b07ca8e1-139c-484c-a46f-8c6c72a16bb5",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Veloce",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 0,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "1257a89b-761d-4fd9-91a6-43eae7ab1c24",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Spensierata",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 10000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "26195e5a-243f-4397-89a2-dc37fd82efc9",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Salita",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 20000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						}
					],
					"Id": "211d0db1-f83b-4ae7-bfc3-3c656eea3bc0",
					"Expanded": false,
					"Horizontal": false,
					"Text": "Corsa",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 160000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "f6d580d5-8327-4f56-aed9-e2e8f590ee2d",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Visualizza il successo !",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 170000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [
						{
							"children": [],
							"Id": "795a5033-8a9b-4629-986c-b2750a2017d3",
							"Expanded": true,
							"Horizontal": false,
							"Text": "energico",
							"Description": null,
							"Volume": 70,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 0,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "ec90cd59-4156-4bc1-a0e9-7b5b90a04a58",
							"Expanded": true,
							"Horizontal": false,
							"Text": "tranquillo",
							"Description": null,
							"Volume": 70,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 10000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "dfc3538b-5476-4fc2-8ca2-68c838ca709b",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Magico",
							"Description": null,
							"Volume": 70,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 20000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						}
					],
					"Id": "f5be0581-06a6-4b52-9492-3e247720da84",
					"Expanded": false,
					"Horizontal": false,
					"Text": "Risvegli",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 180000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "9be71303-b480-44a3-975b-e814286c8d95",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Problems...",
					"Description": null,
					"Volume": 66,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 190000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "5948458d-091a-440c-b832-b02b0c842149",
					"Expanded": true,
					"Horizontal": false,
					"Text": "night  out move out",
					"Description": "",
					"Volume": 50,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 200000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				}
			],
			"Id": "3842d8b4-8c3e-4fc2-bdf1-4625e79e7067",
			"Expanded": false,
			"Horizontal": false,
			"Text": "USI",
			"Description": null,
			"Volume": 100,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 0,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": null
		},
		{
			"children": [
				{
					"children": [
						{
							"children": [],
							"Id": "9ef7b1c0-6c23-4207-86f6-718e7699c10b",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Relazioni",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 0,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "5188a88c-14d2-46f4-a603-48bdbaf6b550",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Mondo",
							"Description": null,
							"Volume": 70,
							"VolumeChanged": true,
							"Color": "FFFDFB",
							"LineColor": null,
							"HorizontalOrder": 10000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": ""
						},
						{
							"children": [],
							"Id": "f621e2ce-1a69-4799-972c-9b7866af4b37",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Love pain",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 20000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "11448c23-6006-4551-8b4a-d6549896602c",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Famiglia",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 30000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "84df3744-85f1-4097-b08c-9f1e72e7069c",
							"Expanded": true,
							"Horizontal": false,
							"Text": "Myself  !",
							"Description": null,
							"Volume": 66,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 40000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						}
					],
					"Id": "f359b0d9-134f-4ac0-825d-6515c019773c",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Amore",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "#FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 0,
					"Selected": false,
					"SequentialPlayback": true,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "99af60fd-75f4-4e14-9f6d-9b6613827d0c",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Brillant/Follia Pazzia",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 10000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "6409415a-ccf1-4360-80c6-3dbc6d454cfd",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Coraggio/Fiducia in se stessi/Believe",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "#FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 20000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "f92dd093-0c99-418d-908d-af7ef62a5a2e",
					"Expanded": true,
					"Horizontal": true,
					"Text": "dark side",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 30000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "b38a130f-273d-4860-8762-999018ba5f9c",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Determinazione/sfida/prepare to fight",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 40000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "f54890f1-af3a-464f-8c70-085ac604c84f",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Forza",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "#FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 50000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "485bf028-2bc9-4ab5-a01c-c6a1bdd44c4b",
					"Expanded": true,
					"Horizontal": true,
					"Text": "fede/Connessione",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": true,
					"Color": "FFFCF4",
					"LineColor": null,
					"HorizontalOrder": 60000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "ff0c7714-8efd-42e8-81f4-f50b0bc905f1",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Entusiasmo state up !",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": true,
					"Color": "FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 70000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "e33553be-85d1-43d5-8433-82c088717672",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Gloria/ maestosità",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": true,
					"Color": "FFFFFF",
					"LineColor": null,
					"HorizontalOrder": 80000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "d931d4b1-4051-43a4-8a88-ff9622fe1524",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Ilarità/Trash",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": "F1FDFF",
					"LineColor": null,
					"HorizontalOrder": 90000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "8a432a29-7090-4980-8b03-d2862b2c04c9",
					"Expanded": false,
					"Horizontal": true,
					"Text": "Joy/Happiness",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 100000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "3014c59a-6ae8-4b20-98d7-f5c6614be79f",
					"Expanded": true,
					"Horizontal": true,
					"Text": "gratitudine/Commozione",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 110000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "14bd9b84-227f-4612-aff6-45814e2b7aa6",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Nostalgia",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 120000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "dea79c58-84da-4063-986a-2462d7973b48",
					"Expanded": false,
					"Horizontal": true,
					"Text": "Pain=Energy, Rivalsa",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": "6963FF",
					"LineColor": null,
					"HorizontalOrder": 130000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": ""
				},
				{
					"children": [],
					"Id": "eaafb5bc-4105-4472-8cc0-2b3b0185e685",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Raffinatezza",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 140000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "780f0fe2-1b66-41cc-b3ac-1294b6f8c1ec",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Spensieratezza",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 150000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "c176698b-42ec-47ad-bfc6-27dd7752360f",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Time/Eternity",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 160000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "7a005f73-fd3f-437e-81e2-322a603f1403",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Velocità",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 170000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "0ba914c0-d413-43dc-8ea6-73cb783e8d6a",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Sensualità",
					"Description": "",
					"Volume": 100,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 180000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "c115ca92-4742-4c56-9899-9f8fc9d68c22",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Avanzamento/progresso",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 190000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "03c5ee54-7f4d-4b8d-be8c-0c5763c24265",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Vittoria/Trionfo",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 200000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "4ef81d2e-840e-4407-b884-b9b831145b23",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Riscaldami  il  cuore",
					"Description": null,
					"Volume": 71,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 210000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "00491301-99ec-4a7a-8676-9b24126133ff",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Libertà",
					"Description": "",
					"Volume": 71,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 220000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "e230528f-0d04-4553-95a3-c35c282a73db",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Confusion",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 230000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "4c506398-600d-4645-b23e-c065946956a3",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Pace/Tranquillità/Relax",
					"Description": "",
					"Volume": 70,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 240000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "89faac3b-14df-40be-b9d7-b2f9f7cc92a1",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Tristezza",
					"Description": null,
					"Volume": 70,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 250000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				}
			],
			"Id": "fa6d1890-6534-4867-b511-dc545ff54301",
			"Expanded": true,
			"Horizontal": false,
			"Text": "EMOZIONI",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": true,
			"Color": "#FFFFFF",
			"LineColor": null,
			"HorizontalOrder": 10000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [
				{
					"children": [
						{
							"children": [],
							"Id": "a90e4ef7-f36e-4a9e-8eb7-459a4e43b967",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Progressivo",
							"Description": "",
							"Volume": 100,
							"VolumeChanged": false,
							"Color": "",
							"LineColor": null,
							"HorizontalOrder": 0,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "420def54-b6af-4530-af9f-cbad872fc0aa",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Classico",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": null,
							"LineColor": null,
							"HorizontalOrder": 10000,
							"Selected": false,
							"SequentialPlayback": false,
							"BackgroundImage": null
						},
						{
							"children": [],
							"Id": "b6562a8a-9210-410c-898b-07c6b87b70cb",
							"Expanded": true,
							"Horizontal": true,
							"Text": "Hard",
							"Description": null,
							"Volume": 100,
							"VolumeChanged": false,
							"Color": "",
							"LineColor": null,
							"HorizontalOrder": 20000,
							"Selected": false,
							"SequentialPlayback": true,
							"BackgroundImage": null
						}
					],
					"Id": "9b71f031-9a88-42e8-9c3d-d274ef3f7b0f",
					"Expanded": false,
					"Horizontal": false,
					"Text": "Rock",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 0,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "3c941658-4297-416b-a82c-e342428bb906",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Funky",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 10000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "a1c81e13-f89b-45bd-a8b4-6ee744002819",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Classic",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 20000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "53201ae3-43c1-4227-8ba6-cc66f9e5d0e8",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Blues e dintorni",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 30000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "9ca95046-9e38-4751-acdf-8c0774fa2cf2",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Jazz e dintorni",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 40000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "12c65d64-eab0-4238-9fd5-2278e7a90795",
					"Expanded": true,
					"Horizontal": true,
					"Text": "My new Italian",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 50000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "3fbbb47f-d0d4-42f7-8560-98907b6c15e3",
					"Expanded": true,
					"Horizontal": true,
					"Text": "My old italian",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 60000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "4c45b57b-9b8d-497a-94bb-c5fe08316a78",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Cartoons",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 70000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "31a52709-a2bb-4b38-a77d-e8a1f73a9ca5",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Videogames",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 80000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "ea04bd36-5f71-401f-a175-4260deba97b6",
					"Expanded": true,
					"Horizontal": true,
					"Text": "pop inglese",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 90000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "d81c9a07-043f-40ff-8b9f-9990fcc5dde6",
					"Expanded": true,
					"Horizontal": true,
					"Text": "masterpieces",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 100000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "9c49c3b7-0c85-40bf-b465-67885600ab3b",
					"Expanded": true,
					"Horizontal": true,
					"Text": "ultraterreno",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 110000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "75d306b4-06cd-4b86-9adf-3c9c5a820759",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Chillout",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 120000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "98b5227a-bfd1-436d-b4c7-951eaa1ad012",
					"Expanded": false,
					"Horizontal": true,
					"Text": "Dance 70",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 130000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "e056ac80-f5d5-46d0-a8b0-8f82aa90a318",
					"Expanded": true,
					"Horizontal": true,
					"Text": "Ottanta",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 140000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "5175f306-e809-4e9f-919f-c6ad18fa2d0e",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Novanta",
					"Description": null,
					"Volume": 66,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 150000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "cb57971e-af5f-4e73-8d14-215c7a29e7af",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Dance  90",
					"Description": null,
					"Volume": 100,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 160000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "ca3c77c1-03fb-457a-959f-685ece199e6b",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Dance  00",
					"Description": null,
					"Volume": 43,
					"VolumeChanged": false,
					"Color": null,
					"LineColor": null,
					"HorizontalOrder": 170000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "2182f8e7-4ccd-4162-a5de-c3eaee732e2b",
					"Expanded": true,
					"Horizontal": false,
					"Text": "new  age / 69",
					"Description": "",
					"Volume": 70,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 180000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				},
				{
					"children": [],
					"Id": "b445c787-36aa-4b1b-81ff-cce43e93372b",
					"Expanded": true,
					"Horizontal": false,
					"Text": "Luigi  Romano",
					"Description": "",
					"Volume": 70,
					"VolumeChanged": false,
					"Color": "",
					"LineColor": null,
					"HorizontalOrder": 190000,
					"Selected": false,
					"SequentialPlayback": false,
					"BackgroundImage": null
				}
			],
			"Id": "f7e02539-d0a7-4a59-9aaa-baf6453336bb",
			"Expanded": true,
			"Horizontal": false,
			"Text": "GENERI",
			"Description": null,
			"Volume": 100,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 20000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": null
		},
		{
			"children": [],
			"Id": "f5af5d72-a52e-44c4-aad8-7fc0c032fcac",
			"Expanded": true,
			"Horizontal": true,
			"Text": "Riunione",
			"Description": "",
			"Volume": 70,
			"VolumeChanged": false,
			"Color": "",
			"LineColor": null,
			"HorizontalOrder": 30000,
			"Selected": false,
			"SequentialPlayback": true,
			"BackgroundImage": null
		},
		{
			"children": [],
			"Id": "56cf5c3c-2b99-47a4-9afd-986b424e8bdf",
			"Expanded": true,
			"Horizontal": true,
			"Text": "Gyui",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 40000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [],
			"Id": "b811e5e8-bb28-4f46-b37e-0dd92f52c3b6",
			"Expanded": true,
			"Horizontal": true,
			"Text": "hb",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 50000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [],
			"Id": "f7d59200-64ec-4d48-b3d0-071530adf836",
			"Expanded": true,
			"Horizontal": true,
			"Text": "vdzvz ",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 60000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		},
		{
			"children": [],
			"Id": "122ca900-6c02-403c-84a0-83049ef19845",
			"Expanded": true,
			"Horizontal": true,
			"Text": "Prova",
			"Description": null,
			"Volume": 70,
			"VolumeChanged": false,
			"Color": null,
			"LineColor": null,
			"HorizontalOrder": 70000,
			"Selected": false,
			"SequentialPlayback": false,
			"BackgroundImage": ""
		}
	],
	"Id": "7ec1a30b-4b15-4ef7-ad31-e429c1a0e94c",
	"Expanded": true,
	"Horizontal": true,
	"Text": "Luigi",
	"Description": "ciao angelo",
	"Volume": 100,
	"VolumeChanged": false,
	"Color": "#FFFFFF",
	"LineColor": "#FFFFFF",
	"HorizontalOrder": -1,
	"Selected": true,
	"SequentialPlayback": false,
	"BackgroundImage": null
};
